name: codiff
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.15=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.3.0
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - basicsr==1.4.2
      - bitsandbytes==0.45.0
      - blinker==1.9.0
      - certifi==2024.12.14
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cmake==3.31.4
      - colorama==0.4.6
      - compressai==1.2.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - decorator==5.1.1
      - diffusers==0.25.0
      - distlib==0.3.9
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - einx==0.3.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - facexlib==0.3.0
      - fairscale==0.4.13
      - filelock==3.17.0
      - filterpy==1.4.5
      - flask==3.1.0
      - fonttools==4.55.5
      - frozendict==2.4.6
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - ftfy==6.3.1
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.70.0
      - huggingface-hub==0.25.0
      - icecream==2.1.4
      - identify==2.6.6
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - iniconfig==2.0.0
      - ipython==8.31.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lightning-utilities==0.14.2
      - lit==18.1.8
      - llvmlite==0.44.0
      - lmdb==1.6.2
      - loralib==0.1.2
      - lpips==0.1.4
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.2.0
      - mypy-extensions==1.0.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numba==0.61.0
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.3.0
      - open-clip-torch==2.20.0
      - openai-clip==1.0.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - peft==0.9.0
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pre-commit==4.1.0
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - protobuf==3.20.3
      - psutil==6.1.1
      - ptflops==0.7.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyiqa==0.1.13
      - pyparsing==3.2.1
      - pyre-extensions==0.0.29
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.3.0
      - pytorch-msssim==1.0.0
      - pytz==2024.2
      - pyyaml==6.0
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.2
      - scikit-image==0.25.0
      - scipy==1.15.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.13.3
      - tb-nightly==2.19.0a20250123
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - thop==0.1.1-2209072238
      - tifffile==2025.1.10
      - timm==1.0.14
      - tokenizers==0.15.2
      - tomli==2.2.1
      - torch==2.0.1
      - torch-geometric==2.6.1
      - torchmetrics==1.7.0
      - torchvision==0.15.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.37.2
      - triton==2.0.0
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - vector-quantize-pytorch==1.22.3
      - virtualenv==20.29.1
      - wandb==0.19.4
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - xformers==0.0.20
      - yapf==0.43.0
      - yarl==1.18.3
      - zipp==3.21.0
